new_project/src/Entity/VideoGames.php
<?php

namespace App\Entity;

use App\Repository\VideoGamesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoGamesRepository::class)]
class VideoGames
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\ManyToOne(inversedBy: 'videoGames')]
    private ?Console $Console = null;

    #[ORM\ManyToOne(inversedBy: 'videoGames')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Console $console = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getConsole(): ?Console
    {
        return $this->Console;
    }

    public function setConsole(?Console $Console): static
    {
        $this->Console = $Console;

        return $this;
    }
}

new_project/src/Form/VideoGamesType.php
<?php

namespace App\Form;

use App\Entity\VideoGames;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoGamesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('genre')
            ->add('release_date')
            ->add('picture')
            ->add('console')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => VideoGames::class,
        ]);
    }
}

new_project/src/Controller/VideoGamesController.php
<?php

namespace App\Controller;

use App\Entity\VideoGames;
use App\Form\VideoGamesType;
use App\Repository\VideoGamesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/video/games')]
class VideoGamesController extends AbstractController
{
    #[Route('/', name: 'app_video_games_index', methods: ['GET'])]
    public function index(VideoGamesRepository $videoGamesRepository): Response
    {
        return $this->render('video_games/index.html.twig', [
            'video_games' => $videoGamesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_video_games_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $videoGame = new VideoGames();
        $form = $this->createForm(VideoGamesType::class, $videoGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($videoGame);
            $entityManager->flush();

            return $this->redirectToRoute('app_video_games_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('video_games/new.html.twig', [
            'video_game' => $videoGame,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_video_games_show', methods: ['GET'])]
    public function show(VideoGames $videoGame): Response
    {
        return $this->render('video_games/show.html.twig', [
            'video_game' => $videoGame,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_video_games_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, VideoGames $videoGame, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VideoGamesType::class, $videoGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_video_games_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('video_games/edit.html.twig', [
            'video_game' => $videoGame,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_video_games_delete', methods: ['POST'])]
    public function delete(Request $request, VideoGames $videoGame, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$videoGame->getId(), $request->request->get('_token'))) {
            $entityManager->remove($videoGame);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_video_games_index', [], Response::HTTP_SEE_OTHER);
    }
}

new_project/templates/video_games/_delete_form.html.twig
<form method="post" action="{{ path('app_video_games_delete', {'id': video_game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video_game.id) }}">
    <button class="btn">Delete</button>
</form>

new_project/templates/video_games/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

new_project/templates/video_games/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit VideoGames{% endblock %}

{% block body %}
    <h1>Edit VideoGames</h1>

    {{ include('video_games/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_video_games_index') }}">back to list</a>

    {{ include('video_games/_delete_form.html.twig') }}
{% endblock %}

new_project/templates/video_games/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}VideoGames index{% endblock %}

{% block body %}
    <h1>Liste des jeux vidéos</h1>

    <a class="btn btn-primary mt-3 mb-3" href="{{ path('app_video_games_new') }}">Ajouter un jeu</a>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Genre</th>
                <th>Release_date</th>
                <th>Picture</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for video_game in video_games %}
            <tr>
                <td>{{ video_game.id }}</td>
                <td>{{ video_game.name }}</td>
                <td>{{ video_game.genre }}</td>
                <td>{{ video_game.releaseDate ? video_game.releaseDate|date('Y-m-d') : '' }}</td>
                <td>{{ video_game.picture }}</td>
                <td>
                    <a href="{{ path('app_video_games_show', {'id': video_game.id}) }}">show</a>
                    <a href="{{ path('app_video_games_edit', {'id': video_game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-danger mt-3 mb-3" href="{{ path('app_console_index') }}">Voir consoles</a>
    <a href="{{ path('app_home') }}">Retour à l'accueil</a>
{% endblock %}

new_project/templates/video_games/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New VideoGames{% endblock %}

{% block body %}
    <h1>Create new VideoGames</h1>

    {{ include('video_games/_form.html.twig') }}

    <a href="{{ path('app_video_games_index') }}">back to list</a>
{% endblock %}

new_project/templates/video_games/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}VideoGames{% endblock %}

{% block body %}
    <h1>VideoGames</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ video_game.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ video_game.name }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ video_game.genre }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ video_game.releaseDate ? video_game.releaseDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ video_game.picture }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_video_games_index') }}">back to list</a>

    <a href="{{ path('app_video_games_edit', {'id': video_game.id}) }}">edit</a>

    {{ include('video_games/_delete_form.html.twig') }}
{% endblock %}